art_space_shop_index:
    path:     /index
    defaults: { _controller: ArtSpaceShopBundle:Default:index }

art_space_shop:
    path:     /
    defaults: { _controller: ArtSpaceShopBundle:Default:index }
    
art_space_shop_pricing:
    path:     /pricing
    defaults: { _controller: ArtSpaceShopBundle:Pricing:pricing }
    
art_space_shop_pricing_section:
    path:     /pricing/{sectionname}
    defaults: { _controller: ArtSpaceShopBundle:Pricing:pricingSection }
    
art_space_shop_pricing_product:
    path:     /pricing/{sectionname}/{productname}
    defaults: { _controller: ArtSpaceShopBundle:Pricing:pricingProduct }
    
art_space_shop_login:
    path:     /login
    defaults: { _controller: ArtSpaceShopBundle:User:login }
    
art_space_shop_register:
    path:     /register
    defaults: { _controller: ArtSpaceShopBundle:User:register}
    
art_space_shop_createdata:
    path:     /createdata
    defaults: { _controller: ArtSpaceShopBundle:CreateData:index }
    
art_space_shop_login_check:
    path:     /logincheck

art_space_shop_logout:
    path:     /logout
    
art_space_shop_add_to_cart:
    path:     /addtocart/{productId}
    defaults: { _controller: ArtSpaceShopBundle:User:addToCart}
    
art_space_shop_cart:
    path:     /cart
    defaults: { _controller: ArtSpaceShopBundle:User:viewCart}
    
art_space_shop_submit_cart:
    path:     /submitcart
    defaults: { _controller: ArtSpaceShopBundle:User:submitCart}
    
art_space_shop_increase_quantity:
    path:     /increasequantity/{cartItemId}
    defaults: { _controller: ArtSpaceShopBundle:User:increaseQuantity}

art_space_shop_decrease_quantity:
    path:     /decreasequantity/{cartItemId}
    defaults: { _controller: ArtSpaceShopBundle:User:decreaseQuantity}
    
art_space_shop_past_order:
    path:     /pastorder/{userid}
    defaults: { _controller: ArtSpaceShopBundle:User:pastOrder}