security:
    encoders:
        ArtSpace\ShopBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: ArtSpaceShopBundle:User, property: username }

    firewalls:
        artSpace_area:
            pattern:    ^/
            http_basic: ~
            anonymous:  ~
            form_login:
                login_path:  /login
                check_path:  /logincheck
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/pricing, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
